# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

trigger:
  branches:
    include:
      - main
      - develop

  paths:
    exclude:
      - .gitignore
      - .gitattributes
      - .gitmodules
      - .github/*
      - LICENSE.md
      - README.md
      - NuGet.Config
      - assets/*
      - UnitsNet/*

  tags:
    include:
      - v*

# PR always trigger build
pr:
  autoCancel: true

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

variables:
  - name: DOTNET_NOLOGO
    value: true  
  - group: sign-client-credentials
  - name: buildPlatform
    value: 'Any CPU'  
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: 'nanoFramework.UnitsNet.sln'  

pool:
  vmImage: 'windows-latest'

steps:

- template: azure-pipelines-templates/class-lib-build-only.yml@templates
  parameters:
    skipSonarCloudAnalysis: true
    runUnitTests: false

- powershell: |
    $generatedCodePath = "$(Build.SourcesDirectory)\nanoFramework.UnitsNet\GeneratedCode"

    Get-ChildItem -Path $generatedCodePath -Directory | ForEach-Object {
        $nuspec = Get-ChildItem -Path $_.FullName -Filter "*.nuspec" -File | Select-Object -First 1

        if ($nuspec) {
            Write-Host "Packing $($nuspec.Name)..."
            nuget pack $nuspec.FullName -Version $(MY_NUGET_VERSION) -Symbols -SymbolPackageFormat snupkg -OutputDirectory "$(Build.ArtifactStagingDirectory)"
            if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to pack $($nuspec.Name)"
                exit 1
            }
        }
    }
  condition: >-
    and(
      succeeded(),
      eq(variables['StartReleaseCandidate'], false)
    )
  displayName: Package UnitsNet

- task: DotNetCoreCLI@2
  displayName: Install Sign Client CLI
  condition: >-
    and(
      succeeded(),
      eq(variables['StartReleaseCandidate'], false),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . sign --version 0.9.1-beta.23530.1

- pwsh: |
    .\sign code azure-key-vault `
    "**/*.nupkg" `
    --base-directory "$(Build.ArtifactStagingDirectory)" `
    --description "$(Build.Repository.Name)" `
    --description-url "https://github.com/$(Build.Repository.Name)" `
    --azure-key-vault-tenant-id "$(SignTenantId)" `
    --azure-key-vault-client-id "$(SignClientId)" `
    --azure-key-vault-client-secret "$(SignClientSecret)" `
    --azure-key-vault-certificate "$(SignKeyVaultCertificate)" `
    --azure-key-vault-url "$(SignKeyVaultUrl)" `
    --timestamp-url http://timestamp.digicert.com
  displayName: Sign packages
  continueOnError: true
  condition: >-
    and(
      succeeded(),
      eq(variables['StartReleaseCandidate'], false),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )

# publish artifacts (only possible if this is not a PR originated on a fork)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: deployables
    artifactType: pipeline
  condition: >-
    and(
      succeeded(),
      eq(variables['StartReleaseCandidate'], false),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  displayName: Publish deployables artifacts

# push NuGet class lib package to NuGet (happens on every build except PRs)
- task: NuGetCommand@2
  condition: >-
    and(
      succeeded(),
      eq(variables['System.PullRequest.PullRequestId'], ''),
      not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')),
      eq(variables['StartReleaseCandidate'], false),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  continueOnError: true
  displayName: Push NuGet packages to NuGet
  inputs:
    command: push
    nuGetFeedType: external
    allowPackageConflicts: true
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    includeSymbols: true
    publishFeedCredentials: 'NuGet-$(System.TeamProject)'

# step from template @ nf-tools repo
# report error
- template: azure-pipelines-templates/discord-webhook-task.yml@templates  
  parameters:
    workingDirectory: 'nanoFramework.IoT.Device'
    status: 'failure'
    webhookUrl: '$(DiscordWebhook)'
    message: ''
